# Generated by Django 5.0.4 on 2024-05-13 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.TextField()),
                ('description', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='C:/Users/Stephane/Documents/GESTION DU COURRIER/courrier/media')),
                ('date', models.DateField()),
                ('urgence', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courriers_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courriers_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rappel', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.courrier')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
